/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alumno
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        CentroComercial = new javax.swing.JMenu();
        Localidad = new javax.swing.JMenuItem();
        Cine = new javax.swing.JMenu();
        Nombre = new javax.swing.JMenuItem();
        SalaCine = new javax.swing.JMenu();
        Numero = new javax.swing.JMenuItem();
        NumeroButacas = new javax.swing.JMenuItem();
        Entrada = new javax.swing.JMenu();
        TipodeEntrada = new javax.swing.JMenuItem();
        Butaca = new javax.swing.JMenuItem();
        Estreno = new javax.swing.JMenu();
        Titulo = new javax.swing.JMenuItem();
        ActordePersonaje = new javax.swing.JMenuItem();
        Funcion = new javax.swing.JMenu();
        Horario = new javax.swing.JMenuItem();
        Pelicula = new javax.swing.JMenuItem();
        TipodeFuncion = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem5.setText("jMenuItem5");

        jMenu10.setText("jMenu10");

        jMenu12.setText("jMenu12");

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CentroComercial.setText("Centro Comercial");

        Localidad.setText("Localidad");
        Localidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocalidadActionPerformed(evt);
            }
        });
        CentroComercial.add(Localidad);

        Cine.setText("Cine");

        Nombre.setText("Nombre");
        Cine.add(Nombre);

        CentroComercial.add(Cine);

        jMenuBar1.add(CentroComercial);

        SalaCine.setText("Sala de Cine");

        Numero.setText("Numero");
        SalaCine.add(Numero);

        NumeroButacas.setText("Numero de Butacas");
        SalaCine.add(NumeroButacas);

        jMenuBar1.add(SalaCine);

        Entrada.setText("Entrada");

        TipodeEntrada.setText("Tipo de Entrada");
        Entrada.add(TipodeEntrada);

        Butaca.setText("Butaca");
        Entrada.add(Butaca);

        Estreno.setText("Estreno");

        Titulo.setText("Titulo");
        Estreno.add(Titulo);

        ActordePersonaje.setText("Actor de Personaje");
        Estreno.add(ActordePersonaje);

        Entrada.add(Estreno);

        Funcion.setText("Funcion");

        Horario.setText("Horario");
        Funcion.add(Horario);

        Pelicula.setText("Pelicula");
        Pelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PeliculaActionPerformed(evt);
            }
        });
        Funcion.add(Pelicula);

        TipodeFuncion.setText("Tipo de Funcion");
        Funcion.add(TipodeFuncion);

        Entrada.add(Funcion);

        jMenuBar1.add(Entrada);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 201, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LocalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LocalidadActionPerformed

    private void PeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PeliculaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ActordePersonaje;
    private javax.swing.JMenuItem Butaca;
    private javax.swing.JMenu CentroComercial;
    private javax.swing.JMenu Cine;
    private javax.swing.JMenu Entrada;
    private javax.swing.JMenu Estreno;
    private javax.swing.JMenu Funcion;
    private javax.swing.JMenuItem Horario;
    private javax.swing.JMenuItem Localidad;
    private javax.swing.JMenuItem Nombre;
    private javax.swing.JMenuItem Numero;
    private javax.swing.JMenuItem NumeroButacas;
    private javax.swing.JMenuItem Pelicula;
    private javax.swing.JMenu SalaCine;
    private javax.swing.JMenuItem TipodeEntrada;
    private javax.swing.JMenuItem TipodeFuncion;
    private javax.swing.JMenuItem Titulo;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    // End of variables declaration//GEN-END:variables
}
